ENV_FILE=.env


run:
	@DB_PASSWORD=$(DB_PASSWORD) SMTP_HOST=$(SMTP_HOST) SMTP_PORT=$(SMTP_PORT) SMTP_USER=$(SMTP_USER) SMTP_PASS=$(SMTP_PASS) GEOIP_DB_PATH=$(GEO_DB_FILE)  DB_NAME=$(DB_NAME) DB_HOST=$(DB_HOST) DB_PORT=$(DB_PORT) DB_USER=$(DB_USER) && go run *.go